### ISSUE TITLE
[EPIC] Re-org data science projects

### ISSUE THREAD

**Issue by oindrillac** [operate-first/operate-first.github.io-old#265]
Let's make all projects on the DS section on the website consistent as per our discussion in https://github.com/operate-first/operate-first.github.io/issues/252
Each project will follow the format followed by the [AI 4 CI ](https://www.operate-first.cloud/data-science/ocp-ci-analysis/)project.

> * Overview
> * Get Started
> * How to Contribute
> * Content

Each of the following projects will have a section of their own:

- [x] Data Science Workflows - https://github.com/aicoe-aiops/data-science-workflows/issues/36
- [x] AI Supported Continuous Integration
- [x] Categorical Encoding - https://github.com/aicoe-aiops/categorical-encoding/pull/27
- [x] Cloud Price Analysis - https://github.com/aicoe-aiops/cloud-price-analysis-public/pull/17
- [x] #272
- [x] #273
- [x] Hard Drive Failure Prediction - https://github.com/aicoe-aiops/ceph_drive_failure/pull/47
- [x] #276
- [x] #274
- [x] #280
- [x] #275

**Comment by amsaparov** [comment]
@oindrillac 
Margaret and I are working on the Data Science Workflows, and we had a few questions - 
1. Should "Get Started" include the information that is currently the "overview" on the website for Data Science Workflows, or should that go under "How to Contribute"?
2. Where should the current Project Template and Guidelines for reviewing code go? (How to Contribute?)
3. Should the "Data Science Projects" tab for Data Science Workflows contain the "Projects Overview" that is currently under Data Science Projects on the website?

**Comment by oindrillac** [comment]
@amsaparov @margarethaley thanks for taking this up.
I think the primary goal of re-organizing the data-science workflows section would be to "_familiarize anybody landing on the section with the data science workflow that we follow, how they can contribute as well as what are our ongoing initiatives_"

A good way to organize this, I think could be 
1. **Overview** - This can give a brief high-level overview of what we do and what the Data Science section on the website is about. From my understanding, the section mainly contains info on "Examples of data science projects and workflows for the data science users that want to learn about data science on ODH."
2. **Get Started** - This sub-section would contain information and templates that someone could use to get started with DS projects. We need to modify this [workflow](https://www.operate-first.cloud/data-science/data-science-workflows/), as it is a bit outdated, to help someone understand how we typically get started with DS projects and the process we follow while performing DS on the operate first environment. Here, we can create several individual docs/ link to some videos/ documents that already exist. 
This sub-section can consist a getting-started workflow with more information and/or individual documents for each of the following:
      -  how we  define a project doc, (pt 1, 2, 3 [here](https://www.operate-first.cloud/data-science/data-science-workflows/))
      -  create git repos from templates, (pt 6 [here](https://www.operate-first.cloud/data-science/data-science-workflows/))
      -  set up aicoe CI for our repos, (we can create a short document for this)
      -  create project boards and set up issues/milestones for stages of the project),  (pt 4 [here](https://www.operate-first.cloud/data-science/data-science-workflows/))
      -  develop on operate first JH, monitor our workloads using grafana dashboards ( we can link to our JH instance, link to troubleshooting [runbooks](https://www.operate-first.cloud/users/sre/runbooks/jupyterhub.md), the dashboards that exist currently and link an upcoming Espresso video by @Shreyanand once released)
      -  how we manage dependencies (we can create a short document for this/ expand within this doc)
      -  contribute via PRs, ( this can be a short paragraph explaining our process)
      -  how we review PRs, ( link to the doc [here](https://www.operate-first.cloud/data-science/data-science-workflows/docs/guidelines-for-reviewing-datascience-code.md))
      -  kinds of deliverables we generate (eg: slides, blogs, videos etc), 
      -  create JH images for the project, (link to the [video and guide](https://www.operate-first.cloud/users/data-science-workflows/docs/create_and_deploy_jh_image.md) )
      -  create automated model workflows and serve models (link to video [here](https://www.youtube.com/watch?v=bh5WpKq3W7Y&t=1s))
3. **How to Contribute** - This section could share information and links on everything necessary for someone to contribute to our work. (eg: Info on PR reviews, launching project images on JH, opening issues on our various repos etc)
4. **Data Science Projects** - This can point to the doc here https://www.operate-first.cloud/data-science/.

**Comment by oindrillac** [comment]
The opf website [Data Science section](https://www.operate-first.cloud/data-science/data-science-workflows/) looks much more organized in comparison to before. Thanks to @margarethaley and @amsaparov for creating documentation for the Data Science Workflows section and others for reorganizing the repos! 🎉 

For the repos remaining to be re-organized, please follow the same structure as others and modify the [data-science.yaml](https://github.com/operate-first/operate-first.github.io/blob/master/config/data-science.yaml) to add your project to the side panel 🙂
